### ISSUE TITLE
Archive with tar format

### ISSUE THREAD

**Issue by caoli5288** [ojdkbuild/contrib_jdk8u-ci#1]
Zip archive format unfriendly to Linux user
It drop executable permissions.

**Comment by ojdkbuild** [comment]
Hi,

> Zip archive format unfriendly to Linux user

Citation needed :)

> It drop executable permissions.

Could you please be more specific on this, that is what I see:

    $ cat /etc/redhat-release
    CentOS Linux release 7.4.1708 (Core)
    $ curl -LO https://github.com/ojdkbuild/contrib_jdk8u-ci/releases/download/jdk8u171-b11/jdk-8u171-ojdkbuild-linux-x64.zip
    $ unzip -q jdk-8u171-ojdkbuild-linux-x64.zip
    $ ls -l ./jdk-8u171-ojdkbuild-linux-x64/bin/java
    -rwxr-xr-x 1 alex alex 7414 Apr 27 15:27 ./jdk-8u171-ojdkbuild-linux-x64/bin/java
    $ ls -l ./jdk-8u171-ojdkbuild-linux-x64/LICENSE
    -r--r--r-- 1 alex alex 19274 Apr 27 15:27 ./jdk-8u171-ojdkbuild-linux-x64/LICENSE

**Comment by caoli5288** [comment]
Sorry. seems my mistake. It was my other operation that led files loss executable , not the zip problem.
